const products = [
    {
        _id:'1',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: 'images/airpods.jpg',
        description: 'Bluetooth technology lets you connect',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id:'2',
        name: 'Iphone 11 Pro 256GB Memory',
        image: '/images/phone.jpg',
        description: 'Introducing the Iphone 11 pro. A Beautifull phone with high quality camera',
        brand: 'Apple',
        category: 'Electronics',
        price: 599.99,
        countInStock: 8,
        rating: 4,
        numReviews: 8,
    },
    {
        _id:'3',
        name: 'Cannon EOS 800 DSLR Camra',
        image: '/images/camera.jpg',
        description: 'Characterized by versatile imaging specs, the canon EOS BOD CAMERA',
        brand: 'cSNNON',
        category: 'Electronics',
        price: 929.99,
        countInStock: 10,
        rating: 2,
        numReviews: 12,
    },
    {
        _id:'4',
        name: 'Sony Playstation 4 Pro White Version',
        image: '/images/playstation.jpg',
        description: 'The ultimate home entertainment center starts with playstation.',
        brand: 'Sony',
        category: 'Electronics',
        price: 389.99,
        countInStock: 10,
        rating: 5,
        numReviews: 12,
    },
    {
        _id:'5',
        name: 'Logitech G-series Gaming Mouse',
        image: '/images/mouse.jpg',
        description: 'Get a better handle on your game',
        brand: 'logitech',
        category: 'Electronics',
        price: 49.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id:'6',
        name: 'Amazon Echo Dot 3rd Generator',
        image: '/images/alexa.jpg',
        description: 'Our Most populor smart  speaker with a fabric design.',
        brand: 'Amazon',
        category: 'Electronics',
        price: 29.99,
        countInStock: 0,
        rating: 4.5,
        numReviews: 12,
    },
]

export default products